backend:
  name: git-gateway
publish_mode: editorial_workflow

media_folder: "content/post/images/uploaded"
public_folder: "/images/uploaded"
locale: "ja"

collections:
  - name: 'post'
    label: "Post"
    folder: "content/post"
    create: true
    extension: 'json'
    # slug: '{{fields.slug}}'
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日時", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "最終更新", name: "update", default: "", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", required: false}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image", allow_multiple: false}
      - {label: "本文", name: "body", widget: "markdown"}
